
  - target_user: 
      user_name: "target_user_1"
      sha256: "fldsjl"
    questions:
      - question: "What is machine learning?"
        sha256: "fldsjl"
      - question: "How does neural network training work?"
        sha256: "fldsjl"
      - question: "What are the benefits of cloud computing?"
        sha256: "fldsjl"
      - question: "How do I reset my password?"
        sha256: "fldsjl"
      - question: "What is our company's mission statement?"
        sha256: "fldsjl"
    ai_app_ids:
      - ai_app_name: "ai_app_1"
        sha256: "fldsjl"
      - ai_app_name: "ai_app_2"
        sha256: "fldsjl"
      - ai_app_name: "ai_app_3"
        sha256: "fldsjl"
  - target_user: 
      user_name: "target_user_2"
      sha256: "fldsjl"
    questions:
      - question: "How do I update my profile settings?"
        sha256: "fldsjl"
      - question: "What are the system requirements for this software?"
        sha256: "fldsjl"
      - question: "Can you explain data privacy policies?"
        sha256: "fldsjl"
      - question: "How to troubleshoot connection issues?"
        sha256: "fldsjl"
      - question: "What integrations are available?"
        sha256: "fldsjl"
    ai_app_ids:
      - ai_app_name: "ai_app_1"
        sha256: "fldsjl"
      - ai_app_name: "ai_app_2"
        sha256: "fldsjl"
      - ai_app_name: "ai_app_3"
        sha256: "fldsjl"
  - target_user: 
      user_name: "target_user_3"
      sha256: "fldsjl"
    questions:
      - question: "Show me sales analytics for Q4"
        sha256: "fldsjl"
      - question: "How to generate monthly reports?"
        sha256: "fldsjl"
      - question: "What are our top performing products?"
        sha256: "fldsjl"
      - question: "Can you analyze customer churn data?"
        sha256: "fldsjl"
      - question: "Export user engagement metrics"
        sha256: "fldsjl"
    ai_app_ids:
      - ai_app_name: "ai_app_1"
        sha256: "fldsjl"
      - ai_app_name: "ai_app_2"
        sha256: "fldsjl"
      - ai_app_name: "ai_app_3"
        sha256: "fldsjl"