users-questions-allowed:
  user1:
    - question1
    - question2
    - question3
    - question4
    - question5
    - question6
    - question7
    - question8
    - question9
    - question10
  user2:
    - question1
    - question2
    - question3
    - question4
    - question5
    - question6
    - question7
    - question8
    - question9
    - question10
  user3:
    - question6
    - question7